### ISSUE TITLE
Nothing happens after opening cilent.jar in mac (only on this person`s PC)

### ISSUE THREAD

**Issue by rhashi** [SaherBlueEagle/BlueEagle_jRAT#2]
On windows its working perfectly, but when I run client.jar on mac, it didn't connect to the server.
For mac os i gave port 8080, but still not getting any connection. 

Also, when I run the server SBEjRAT.jar in mac os it gives error. Something like "no SBEjRAT_Instance.jar found"

**Comment by SaherBlueEagle** [comment]
Dear rhashi ; 
please try to focus while watching the tutorials and concentrate on notes i have written in the video consciously 
Best Regards ;
